name: lettutor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Firebase & Auth
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+5
  google_sign_in: ^6.3.0

  # State Management & Persistence
  provider: ^6.1.3
  shared_preferences: ^2.5.3

  # Navigation
  persistent_bottom_nav_bar: ^6.2.1
  page_transition: ^2.2.1

  # UI/UX Widgets
  animated_splash_screen: ^1.3.0
  number_paginator: ^1.1.0
  flutter_countdown_timer: ^4.1.0
  multiselect:
  expandable_text: ^2.3.0
  syncfusion_flutter_calendar: ^29.1.41
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2

  # Media & Images
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  video_player: ^2.8.1
  chewie: ^1.7.1
  image_picker: ^1.1.2
  country_picker: ^2.0.27

  # Utilities
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^29.1.41
  flutter_local_notifications: ^19.1.0
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^12.0.0+1
  flutter_timezone: ^4.1.0
  app_settings: ^6.1.1
  syncfusion_flutter_core: ^29.1.41


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
  generate: true

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "lib/assets/icons/1024.png"
  min_sdk_android: 21
